/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.28).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.rank.api;

import com.rank.entity.Transactions;
import com.rank.model.RequestUserTransaction;
import com.rank.model.TransactionDetail;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import javax.validation.Valid;
import java.util.List;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2022-09-13T11:26:17.148Z")

@Validated
@Api(value = "admin", description = "the admin API")
@RequestMapping(value = "/casino/v1")
public interface AdminApi {

    @ApiOperation(value = "Get player transactions", nickname = "getTransactions", notes = "", response = TransactionDetail.class, tags={ "admin", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "successful operation", response = TransactionDetail.class),
        @ApiResponse(code = 400, message = "Bad request", response = Transactions.class),
        @ApiResponse(code = 412, message = "Precondition Failed"),
        @ApiResponse(code = 413, message = "Payload Too Large"),
        @ApiResponse(code = 429, message = "Too Many Requests in a short period") })
    @RequestMapping(value = "/admin/player/transactions",
        produces = { "application/json" }, 
        method = RequestMethod.POST)
    ResponseEntity<List<TransactionDetail>> getTransactions(@ApiParam(value = "player details" ,required=true )  @Valid @RequestBody RequestUserTransaction body);

}
